name: flutter_portal_test
description: An application to test portal support in Flutter.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xdg_desktop_portal: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
