name: flutter-portal-test
version: git
summary: Application to test portal support in Flutter.
description: |
  Application to test portal support in Flutter.
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
architectures:
  - build-on: amd64
assumes:
  - snapd2.46

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: master
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime:
      rm -r $CRAFT_PART_INSTALL

  flutter-portal-test:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      set -eux
      flutter channel stable
      flutter upgrade
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

apps:
  flutter-portal-test:
    command: bin/flutter_portal_test
    extensions: [gnome]
    plugs:
      - network
      - network-status
